version: '3.4'

services:
  iotedgewebapi:
    image: doveracrpractice.azurecr.io/iotedgewebapi:latest
    build:
      context: .
      dockerfile: IotEdge-WebApi\Dockerfile
    ports:
      - 10000:10000
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.1.0/16
